on: push

# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#       - run: pwd
#       - run: ls
#   job2:
#     runs-on: windows-latest
#     steps:
#       - run: node --version
jobs:
  npm-bulid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build